package com.linkpoint.render.lumiya.drawable

import android.opengl.GLES32
import android.opengl.Matrix
import android.util.Log
import com.linkpoint.assets.MeshData
import com.linkpoint.assets.MeshFace
import com.linkpoint.assets.SkinData
import com.linkpoint.avatar.AvatarSkeleton
import com.linkpoint.protocol.textures.TextureEntryParser
import com.linkpoint.render.geometry.PrimMeshData
import com.linkpoint.render.lumiya.core.LumiyaRenderContext
import com.linkpoint.render.lumiya.glres.GLBufferManager
import com.linkpoint.render.lumiya.shaders.RiggedMeshShaderProgram
import com.linkpoint.render.materials.GlesMaterialTranslator
import com.linkpoint.render.materials.MaterialDescriptor
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.util.UUID
import java.util.concurrent.ConcurrentHashMap

/**
 * Renders SL mesh-asset prims (sculptType 5 / modern uploaded mesh content).
 *
 * Design lineage: `render/prims/MeshPrimRenderer.kt` (Filament path) ported
 * to GL ES 3 VAOs. Each unique mesh asset is compiled into one VAO per
 * face; per-prim instances reference the shared VAOs and carry their own
 * model matrix + per-face material array.
 *
 * Rigged mesh attachments pre-align vertex joint indices to standard avatar
 * skeleton bone indices during compilation and bind host avatar joint UBOs
 * directly to UBO binding point 1 without extra per-attachment UBO allocations.
 */
class DrawableMeshStore {

    companion object {
        private const val TAG = "DrawableMeshStore"
        private val IDENTITY_MATRIX = FloatArray(16).also { Matrix.setIdentityM(it, 0) }
        private val BONE_NAME_TO_INDEX_MAP: Map<String, Int> by lazy {
            AvatarSkeleton.BONE_NAMES.withIndex().associate { it.value to it.index }
        }
    }

    /** Per-mesh-asset GPU buffers, one VAO per face. */
    private data class CompiledMesh(
        val faces: List<GLBufferManager.MeshVAO>,
        /** Per-face AABB extents in mesh-local space (max half-extent). */
        val faceBounds: List<Float>
    )

    /** Per-face per-prim material data. */
    data class FaceMaterial(
        var textureId: UUID = UUID(0L, 0L),
        var textureHandle: Int = 0,
        var normalHandle: Int = 0,
        var metallicRoughnessHandle: Int = 0,
        var emissiveHandle: Int = 0,
        var occlusionHandle: Int = 0,
        var colorR: Float = 1f,
        var colorG: Float = 1f,
        var colorB: Float = 1f,
        var colorA: Float = 1f,
        var scaleS: Float = 1f,
        var scaleT: Float = 1f,
        var offsetS: Float = 0f,
        var offsetT: Float = 0f,
        var rotation: Float = 0f,
        var metallicFactor: Float = 1f,
        var roughnessFactor: Float = 1f,
        var descriptor: MaterialDescriptor? = null
    )

    data class MeshInstance(
        val id: Long,
        val meshId: UUID,
        val modelMatrix: FloatArray = FloatArray(16).also { Matrix.setIdentityM(it, 0) },
        val faces: MutableList<FaceMaterial> = mutableListOf(),
        var aabbHalfX: Float = 0.5f,
        var aabbHalfY: Float = 0.5f,
        var aabbHalfZ: Float = 0.5f,
        var isTransparent: Boolean = false,
        var hostAvatarId: UUID? = null
    )

    private val compiled = ConcurrentHashMap<UUID, CompiledMesh>()
    private val instances = ConcurrentHashMap<Long, MeshInstance>()
    private var bufferManager: GLBufferManager? = null

    var avatarStore: DrawableAvatarStore? = null

    // ── Compilation ──────────────────────────────────────────────────────

    fun upsertMeshPrim(
        id: Long,
        ctx: LumiyaRenderContext,
        posX: Float, posY: Float, posZ: Float,
        scaleX: Float, scaleY: Float, scaleZ: Float,
        rotation: FloatArray? = null,
        meshData: MeshData,
        textureEntry: ByteArray? = null,
        hostAvatarId: UUID? = null
    ): Boolean {
        val mesh = getOrCompile(ctx, meshData) ?: return false

        val instance = instances.getOrPut(id) { MeshInstance(id, meshData.meshId) }
        instance.hostAvatarId = hostAvatarId
        Matrix.setIdentityM(instance.modelMatrix, 0)
        Matrix.translateM(instance.modelMatrix, 0, posX, posY, posZ)
        if (rotation != null && rotation.size >= 16) {
            val tmp = FloatArray(16)
            Matrix.multiplyMM(tmp, 0, instance.modelMatrix, 0, rotation, 0)
            System.arraycopy(tmp, 0, instance.modelMatrix, 0, 16)
        }
        Matrix.scaleM(instance.modelMatrix, 0, scaleX, scaleY, scaleZ)
        instance.aabbHalfX = scaleX * 0.5f
        instance.aabbHalfY = scaleY * 0.5f
        instance.aabbHalfZ = scaleZ * 0.5f

        applyTextureEntry(instance, mesh, textureEntry)
        return true
    }

    fun setHostAvatarId(id: Long, hostAvatarId: UUID?) {
        instances[id]?.hostAvatarId = hostAvatarId
    }

    /**
     * Insert/update a sculpt-map mesh primitive generated by PrimMeshGenerator.
     */
    fun upsertSculptPrim(
        id: Long,
        ctx: LumiyaRenderContext,
        posX: Float, posY: Float, posZ: Float,
        scaleX: Float, scaleY: Float, scaleZ: Float,
        rotation: FloatArray? = null,
        sculptMesh: PrimMeshData,
        textureEntry: ByteArray? = null
    ): Boolean {
        val bm = bufferManager ?: GLBufferManager(ctx.resourceManager).also { bufferManager = it }
        val interleaved = sculptMesh.toInterleavedBuffer()
        val vao = bm.buildVAO(interleaved, sculptMesh.indices, listOf(0 to 3, 1 to 3, 2 to 2))

        val sculptMeshId = UUID(id, id)
        val cm = CompiledMesh(listOf(vao), listOf(0.5f))
        compiled[sculptMeshId] = cm

        val instance = instances.getOrPut(id) { MeshInstance(id, sculptMeshId) }
        Matrix.setIdentityM(instance.modelMatrix, 0)
        Matrix.translateM(instance.modelMatrix, 0, posX, posY, posZ)
        if (rotation != null && rotation.size >= 16) {
            val tmp = FloatArray(16)
            Matrix.multiplyMM(tmp, 0, instance.modelMatrix, 0, rotation, 0)
            System.arraycopy(tmp, 0, instance.modelMatrix, 0, 16)
        }
        Matrix.scaleM(instance.modelMatrix, 0, scaleX, scaleY, scaleZ)
        instance.aabbHalfX = scaleX * 0.5f
        instance.aabbHalfY = scaleY * 0.5f
        instance.aabbHalfZ = scaleZ * 0.5f

        applyTextureEntry(instance, cm, textureEntry)
        return true
    }

    private fun getOrCompile(ctx: LumiyaRenderContext, data: MeshData): CompiledMesh? {
        compiled[data.meshId]?.let { return it }
        if (data.faces.isEmpty()) return null
        val bm = bufferManager ?: GLBufferManager(ctx.resourceManager).also { bufferManager = it }
        val vaos = mutableListOf<GLBufferManager.MeshVAO>()
        val bounds = mutableListOf<Float>()
        try {
            for (face in data.faces) {
                if (face.vertexCount == 0 || face.indexCount == 0) continue
                val vao = uploadFace(bm, face, data.skinData) ?: continue
                vaos.add(vao)
                bounds.add(faceMaxExtent(face))
            }
        } catch (e: Exception) {
            Log.w(TAG, "Mesh compile failed for ${data.meshId}: ${e.message}")
            return null
        }
        if (vaos.isEmpty()) return null
        val cm = CompiledMesh(vaos, bounds)
        compiled[data.meshId] = cm
        return cm
    }

    private fun uploadFace(bm: GLBufferManager, face: MeshFace, skinData: SkinData? = null): GLBufferManager.MeshVAO? {
        if (face.positions.size != face.vertexCount * 3) return null
        if (face.normals.size != face.vertexCount * 3) return null
        if (face.uvs.size != face.vertexCount * 2) return null

        val vertexCount = face.vertexCount
        val bindShape = skinData?.bindShapeMatrix
        val hasValidBindShape = bindShape != null && bindShape.size == 16
        val jointNames = skinData?.jointNames ?: emptyList()

        val rawJoints = face.jointIndices
        val rawWeights = face.weights
        val isRiggedFace = face.isRigged || skinData != null

        val bb = ByteBuffer.allocateDirect(vertexCount * 16 * 4).order(ByteOrder.nativeOrder())

        for (i in 0 until vertexCount) {
            var px = face.positions[i * 3 + 0]
            var py = face.positions[i * 3 + 1]
            var pz = face.positions[i * 3 + 2]
            if (hasValidBindShape) {
                val rx = bindShape!![0] * px + bindShape[4] * py + bindShape[8] * pz + bindShape[12]
                val ry = bindShape[1] * px + bindShape[5] * py + bindShape[9] * pz + bindShape[13]
                val rz = bindShape[2] * px + bindShape[6] * py + bindShape[10] * pz + bindShape[14]
                px = rx; py = ry; pz = rz
            }
            bb.putFloat(px)
            bb.putFloat(py)
            bb.putFloat(pz)

            var nx = face.normals[i * 3 + 0]
            var ny = face.normals[i * 3 + 1]
            var nz = face.normals[i * 3 + 2]
            if (hasValidBindShape) {
                val rnx = bindShape!![0] * nx + bindShape[4] * ny + bindShape[8] * nz
                val rny = bindShape[1] * nx + bindShape[5] * ny + bindShape[9] * nz
                val rnz = bindShape[2] * nx + bindShape[6] * ny + bindShape[10] * nz
                val len = kotlin.math.sqrt(rnx * rnx + rny * rny + rnz * rnz)
                if (len > 1e-6f) {
                    nx = rnx / len; ny = rny / len; nz = rnz / len
                } else {
                    nx = rnx; ny = rny; nz = rnz
                }
            }
            bb.putFloat(nx)
            bb.putFloat(ny)
            bb.putFloat(nz)

            bb.putFloat(face.uvs[i * 2 + 0])
            bb.putFloat(face.uvs[i * 2 + 1])

            var w0 = 0f; var w1 = 0f; var w2 = 0f; var w3 = 0f
            var j0 = 0; var j1 = 0; var j2 = 0; var j3 = 0

            if (isRiggedFace && rawJoints != null && rawWeights != null &&
                rawJoints.size >= (i + 1) * 4 && rawWeights.size >= (i + 1) * 4) {

                val mapJoint = { ji: Int, w: Float ->
                    if (ji >= 0 && ji < jointNames.size && w > 0f) {
                        val name = jointNames[ji]
                        val globalIdx = BONE_NAME_TO_INDEX_MAP[name]
                        if (globalIdx != null) globalIdx to w else 0 to 0f
                    } else 0 to 0f
                }

                val (mappedJ0, mappedW0) = mapJoint(rawJoints[i * 4 + 0], rawWeights[i * 4 + 0])
                val (mappedJ1, mappedW1) = mapJoint(rawJoints[i * 4 + 1], rawWeights[i * 4 + 1])
                val (mappedJ2, mappedW2) = mapJoint(rawJoints[i * 4 + 2], rawWeights[i * 4 + 2])
                val (mappedJ3, mappedW3) = mapJoint(rawJoints[i * 4 + 3], rawWeights[i * 4 + 3])

                val wSum = mappedW0 + mappedW1 + mappedW2 + mappedW3
                if (wSum > 1e-6f) {
                    w0 = mappedW0 / wSum; w1 = mappedW1 / wSum
                    w2 = mappedW2 / wSum; w3 = mappedW3 / wSum
                    j0 = mappedJ0; j1 = mappedJ1; j2 = mappedJ2; j3 = mappedJ3
                }
            }

            bb.putFloat(w0); bb.putFloat(w1); bb.putFloat(w2); bb.putFloat(w3)
            bb.putInt(j0); bb.putInt(j1); bb.putInt(j2); bb.putInt(j3)
        }

        bb.flip()
        return bm.buildSkinnedVAO(bb, face.indices)
    }

    private fun faceMaxExtent(face: MeshFace): Float {
        var maxAbs = 0f
        for (i in face.positions.indices) {
            val a = Math.abs(face.positions[i])
            if (a > maxAbs) maxAbs = a
        }
        return maxAbs
    }

    // ── Mutation ─────────────────────────────────────────────────────────

    fun bindTextureToMatchingFaces(
        id: Long,
        textureId: UUID,
        textureHandle: Int,
        semantic: com.linkpoint.assets.TextureFormatPolicy.TextureSemantic = com.linkpoint.assets.TextureFormatPolicy.TextureSemantic.ALBEDO
    ) {
        val instance = instances[id] ?: return
        instance.faces.forEach { f ->
            if (f.textureId == textureId) {
                when (semantic) {
                    com.linkpoint.assets.TextureFormatPolicy.TextureSemantic.NORMAL -> f.normalHandle = textureHandle
                    com.linkpoint.assets.TextureFormatPolicy.TextureSemantic.METALLIC_ROUGHNESS -> f.metallicRoughnessHandle = textureHandle
                    com.linkpoint.assets.TextureFormatPolicy.TextureSemantic.EMISSIVE -> f.emissiveHandle = textureHandle
                    com.linkpoint.assets.TextureFormatPolicy.TextureSemantic.OCCLUSION -> f.occlusionHandle = textureHandle
                    else -> f.textureHandle = textureHandle
                }
            }
        }
    }

    fun removePrim(id: Long) {
        instances.remove(id)
    }

    fun clear() {
        instances.clear()
    }

    fun destroy() {
        instances.clear()
        compiled.values.forEach { mesh ->
            mesh.faces.forEach { vao -> bufferManager?.destroyVAO(vao) }
        }
        compiled.clear()
    }

    fun snapshot(): Collection<MeshInstance> = instances.values

    // ── Draw ─────────────────────────────────────────────────────────────

    fun drawOpaque(ctx: LumiyaRenderContext, avatarStore: DrawableAvatarStore? = this.avatarStore) {
        if (instances.isEmpty()) return
        val primProgram = ctx.primProgram
        val riggedProgram = ctx.riggedMeshProgram

        primProgram?.use()
        primProgram?.setLighting(
            ctx.sunDirectionX, ctx.sunDirectionY, ctx.sunDirectionZ,
            ctx.sunColorR, ctx.sunColorG, ctx.sunColorB,
            ctx.ambientColorR, ctx.ambientColorG, ctx.ambientColorB
        )

        riggedProgram?.use()
        riggedProgram?.setLighting(
            ctx.sunDirectionX, ctx.sunDirectionY, ctx.sunDirectionZ,
            ctx.sunColorR, ctx.sunColorG, ctx.sunColorB,
            ctx.ambientColorR, ctx.ambientColorG, ctx.ambientColorB
        )

        for (instance in instances.values) {
            if (instance.isTransparent) continue
            if (!instanceInFrustum(ctx, instance)) continue

            val hostAvatar = instance.hostAvatarId?.let { avatarStore?.getAvatar(it) }
            if (hostAvatar != null && hostAvatar.jointUBO != 0 && riggedProgram != null) {
                riggedProgram.use()
                drawRiggedInstance(riggedProgram, instance, hostAvatar)
            } else if (primProgram != null) {
                primProgram.use()
                drawInstance(primProgram, instance)
            }
        }
        GLES32.glBindVertexArray(0)
    }

    fun drawTransparent(ctx: LumiyaRenderContext, avatarStore: DrawableAvatarStore? = this.avatarStore) {
        if (instances.isEmpty()) return
        val primProgram = ctx.primProgram
        val riggedProgram = ctx.riggedMeshProgram

        primProgram?.use()
        primProgram?.setLighting(
            ctx.sunDirectionX, ctx.sunDirectionY, ctx.sunDirectionZ,
            ctx.sunColorR, ctx.sunColorG, ctx.sunColorB,
            ctx.ambientColorR, ctx.ambientColorG, ctx.ambientColorB
        )

        riggedProgram?.use()
        riggedProgram?.setLighting(
            ctx.sunDirectionX, ctx.sunDirectionY, ctx.sunDirectionZ,
            ctx.sunColorR, ctx.sunColorG, ctx.sunColorB,
            ctx.ambientColorR, ctx.ambientColorG, ctx.ambientColorB
        )

        val sorted = instances.values
            .filter { it.isTransparent && instanceInFrustum(ctx, it) }
            .sortedByDescending {
                val dx = it.modelMatrix[12] - ctx.cameraPositionX
                val dy = it.modelMatrix[13] - ctx.cameraPositionY
                val dz = it.modelMatrix[14] - ctx.cameraPositionZ
                dx * dx + dy * dy + dz * dz
            }

        for (instance in sorted) {
            val hostAvatar = instance.hostAvatarId?.let { avatarStore?.getAvatar(it) }
            if (hostAvatar != null && hostAvatar.jointUBO != 0 && riggedProgram != null) {
                riggedProgram.use()
                drawRiggedInstance(riggedProgram, instance, hostAvatar)
            } else if (primProgram != null) {
                primProgram.use()
                drawInstance(primProgram, instance)
            }
        }
        GLES32.glBindVertexArray(0)
    }

    private fun drawInstance(
        program: com.linkpoint.render.lumiya.shaders.PrimShaderProgram,
        instance: MeshInstance
    ) {
        val mesh = compiled[instance.meshId] ?: return
        program.setModelMatrix(instance.modelMatrix)
        for ((faceIdx, vao) in mesh.faces.withIndex()) {
            val face = instance.faces.getOrNull(faceIdx) ?: continue
            val matDescriptor = face.descriptor ?: MaterialDescriptor(
                baseColor = MaterialDescriptor.Float4(face.colorR, face.colorG, face.colorB, face.colorA),
                baseColorTexture = if (face.textureHandle != 0) MaterialDescriptor.TextureRef(face.textureId, face.textureId) else null,
                metallicFactor = face.metallicFactor,
                roughnessFactor = face.roughnessFactor,
                uvTransform = MaterialDescriptor.UvTransform(face.scaleS, face.scaleT, face.offsetS, face.offsetT, face.rotation)
            )
            val bindings = GlesMaterialTranslator.TextureBindings(
                baseColorHandle = face.textureHandle,
                normalHandle = face.normalHandle,
                metallicRoughnessHandle = face.metallicRoughnessHandle,
                emissiveHandle = face.emissiveHandle,
                occlusionHandle = face.occlusionHandle
            )
            GlesMaterialTranslator.apply(program, matDescriptor, bindings)
            GLES32.glBindVertexArray(vao.vao)
            val type = if (vao.useIntIndices) GLES32.GL_UNSIGNED_INT else GLES32.GL_UNSIGNED_SHORT
            GLES32.glDrawElements(GLES32.GL_TRIANGLES, vao.indexCount, type, 0)
        }
    }

    private fun drawRiggedInstance(
        program: RiggedMeshShaderProgram,
        instance: MeshInstance,
        hostAvatar: DrawableAvatarStore.AvatarInstance
    ) {
        val mesh = compiled[instance.meshId] ?: return
        program.setModelMatrix(instance.modelMatrix)
        program.setBindShapeMatrix(IDENTITY_MATRIX)
        program.setJointCount(hostAvatar.jointCount)
        GLES32.glBindBufferBase(GLES32.GL_UNIFORM_BUFFER, 1, hostAvatar.jointUBO)

        for ((faceIdx, vao) in mesh.faces.withIndex()) {
            val face = instance.faces.getOrNull(faceIdx) ?: continue
            program.setColor(face.colorR, face.colorG, face.colorB, face.colorA)
            program.setUseTexture(face.textureHandle != 0)
            program.setTextureSampler(0)
            program.setTexMatrix(buildTexMatrix(face))

            if (face.textureHandle != 0) {
                GLES32.glActiveTexture(GLES32.GL_TEXTURE0)
                GLES32.glBindTexture(GLES32.GL_TEXTURE_2D, face.textureHandle)
            }

            GLES32.glBindVertexArray(vao.vao)
            val type = if (vao.useIntIndices) GLES32.GL_UNSIGNED_INT else GLES32.GL_UNSIGNED_SHORT
            GLES32.glDrawElements(GLES32.GL_TRIANGLES, vao.indexCount, type, 0)
        }
    }

    private fun instanceInFrustum(ctx: LumiyaRenderContext, instance: MeshInstance): Boolean {
        val cx = instance.modelMatrix[12]
        val cy = instance.modelMatrix[13]
        val cz = instance.modelMatrix[14]
        return ctx.frustumCuller.isAABBVisible(
            cx - instance.aabbHalfX, cy - instance.aabbHalfY, cz - instance.aabbHalfZ,
            cx + instance.aabbHalfX, cy + instance.aabbHalfY, cz + instance.aabbHalfZ
        )
    }

    // ── Per-face material assembly ───────────────────────────────────────

    private fun applyTextureEntry(
        instance: MeshInstance,
        mesh: CompiledMesh,
        textureEntry: ByteArray?
    ) {
        val faceCount = mesh.faces.size
        while (instance.faces.size < faceCount) instance.faces.add(FaceMaterial())
        while (instance.faces.size > faceCount) instance.faces.removeAt(instance.faces.lastIndex)

        if (textureEntry == null || textureEntry.isEmpty()) return
        val parsed = try {
            TextureEntryParser.parseFull(textureEntry, faceCount)
        } catch (t: Throwable) { null } ?: return

        for (i in 0 until faceCount) {
            val src = parsed.getOrNull(i) ?: continue
            val dst = instance.faces[i]
            if (dst.textureId != src.textureId) {
                dst.textureId = src.textureId
                dst.textureHandle = 0
            }
            dst.colorR = src.colorR
            dst.colorG = src.colorG
            dst.colorB = src.colorB
            dst.colorA = src.colorA
            dst.scaleS = src.scaleS
            dst.scaleT = src.scaleT
            dst.offsetS = src.offsetS
            dst.offsetT = src.offsetT
            dst.rotation = src.rotation
        }
        instance.isTransparent = instance.faces.any { it.colorA < 0.999f }
    }

    private fun buildTexMatrix(face: FaceMaterial): FloatArray {
        val m = FloatArray(16)
        Matrix.setIdentityM(m, 0)
        Matrix.translateM(m, 0, 0.5f + face.offsetS, 0.5f + face.offsetT, 0f)
        if (face.rotation != 0f) {
            Matrix.rotateM(m, 0, Math.toDegrees(face.rotation.toDouble()).toFloat(), 0f, 0f, 1f)
        }
        Matrix.scaleM(m, 0, face.scaleS, face.scaleT, 1f)
        Matrix.translateM(m, 0, -0.5f, -0.5f, 0f)
        return m
    }
}
