package com.linkpoint.ui.components.linkpoint2.tokens

import androidx.compose.ui.graphics.Color

/**
 * Generated Design Tokens from tokens.json.
 * DO NOT EDIT DIRECTLY. Generated by tools/token_gen/cli.py
 */
object GeneratedTokens {
    object Color {
        object Status {
            val Online = Color(0xFF4CAF50)
            val Offline = Color(0xFFF44336)
            val Degraded = Color(0xFFFF9800)
            val Unknown = Color(0xFF9E9E9E)
            val Success = Color(0xFF7CFFD8)
            val Warning = Color(0xFFFFD56D)
            val Unsaved = Color(0xFFFF9800)
        }
        object Editor {
            val AppbarBackground = Color(0xFF252526)
            val Background = Color(0xFF1E1E1E)
            val PanelBackground = Color(0xFF2D2D2D)
            val Divider = Color(0xFF3C3C3C)
            val Text = Color(0xFFD4D4D4)
            val TextMuted = Color(0xFFB0B0B0)
            val TextDim = Color(0xFF808080)
        }
        object Scene {
            val Background = Color(0xFF000000)
            val Shadow = Color(0x88000000)
        }
        object Aurora {
            val Color1 = Color(0x386DE8FF)
            val Color2 = Color(0x388C7CFF)
            val Color3 = Color(0x287CFFD8)
        }
        object Glass {
            val Background = Color(0x8C101C33)
            val Stroke = Color(0x14FFFFFF)
        }
        val CoordColor = Color(0xFFB5C7E9)
        val OnSurfaceDim = Color(0xFFB5C7E9)
        val OutlineSubtle = Color(0xFF334364)
        val UnreadBadge = Color(0xFF6DE8FF)
        val OnUnreadBadge = Color(0xFF03212A)
        val HudBackground = Color(0xAA000000)
        val HudStroke = Color(0x33FFFFFF)
    }
}
