/*
 * Decompiled with CFR 0.152.
 */
package com.vivox.service

import com.vivox.service.VxClientProxyJNI

class ND_ERROR {
    ND_ERROR ND_E_CANT_CONNECT_TO_ECHO_SERVER = ND_ERROR("ND_E_CANT_CONNECT_TO_ECHO_SERVER")
    ND_ERROR ND_E_CANT_CONTACT_STUN_SERVER_ON_UDP_PORT_3478 = ND_ERROR("ND_E_CANT_CONTACT_STUN_SERVER_ON_UDP_PORT_3478")
    ND_ERROR ND_E_CANT_CONVERT_LOCAL_IP_ADDRESS = ND_ERROR("ND_E_CANT_CONVERT_LOCAL_IP_ADDRESS")
    ND_ERROR ND_E_CANT_CREATE_TCP_SOCKET = ND_ERROR("ND_E_CANT_CREATE_TCP_SOCKET")
    ND_ERROR ND_E_CANT_FIND_SENDECHO2_PROCADDR = ND_ERROR("ND_E_CANT_FIND_SENDECHO2_PROCADDR")
    ND_ERROR ND_E_CANT_ICMP = ND_ERROR("ND_E_CANT_ICMP")
    ND_ERROR ND_E_CANT_LOAD_ICMP_LIBRARY = ND_ERROR("ND_E_CANT_LOAD_ICMP_LIBRARY")
    ND_ERROR ND_E_CANT_RESOLVE_ROOT_DNS_SERVER = ND_ERROR("ND_E_CANT_RESOLVE_ROOT_DNS_SERVER")
    ND_ERROR ND_E_CANT_RESOLVE_VIVOX_UDP_SERVER = ND_ERROR("ND_E_CANT_RESOLVE_VIVOX_UDP_SERVER")
    ND_ERROR ND_E_ECHO_SERVER_CANT_ALLOCATE_MEDIA_SOCKET = ND_ERROR("ND_E_ECHO_SERVER_CANT_ALLOCATE_MEDIA_SOCKET")
    ND_ERROR ND_E_ECHO_SERVER_CANT_ALLOCATE_SIP_SOCKET = ND_ERROR("ND_E_ECHO_SERVER_CANT_ALLOCATE_SIP_SOCKET")
    ND_ERROR ND_E_ECHO_SERVER_CANT_RESOLVE_NAME = ND_ERROR("ND_E_ECHO_SERVER_CANT_RESOLVE_NAME")
    ND_ERROR ND_E_ECHO_SERVER_LOGIN_RECV_FAILED = ND_ERROR("ND_E_ECHO_SERVER_LOGIN_RECV_FAILED")
    ND_ERROR ND_E_ECHO_SERVER_LOGIN_RECV_FAILED_TIMEOUT = ND_ERROR("ND_E_ECHO_SERVER_LOGIN_RECV_FAILED_TIMEOUT")
    ND_ERROR ND_E_ECHO_SERVER_LOGIN_RESPONSE_FAILED_STATUS = ND_ERROR("ND_E_ECHO_SERVER_LOGIN_RESPONSE_FAILED_STATUS")
    ND_ERROR ND_E_ECHO_SERVER_LOGIN_RESPONSE_MISSING_AUDIORTCP = ND_ERROR("ND_E_ECHO_SERVER_LOGIN_RESPONSE_MISSING_AUDIORTCP")
    ND_ERROR ND_E_ECHO_SERVER_LOGIN_RESPONSE_MISSING_AUDIORTP = ND_ERROR("ND_E_ECHO_SERVER_LOGIN_RESPONSE_MISSING_AUDIORTP")
    ND_ERROR ND_E_ECHO_SERVER_LOGIN_RESPONSE_MISSING_SESSIONID = ND_ERROR("ND_E_ECHO_SERVER_LOGIN_RESPONSE_MISSING_SESSIONID")
    ND_ERROR ND_E_ECHO_SERVER_LOGIN_RESPONSE_MISSING_SIPPORT = ND_ERROR("ND_E_ECHO_SERVER_LOGIN_RESPONSE_MISSING_SIPPORT")
    ND_ERROR ND_E_ECHO_SERVER_LOGIN_RESPONSE_MISSING_STATUS = ND_ERROR("ND_E_ECHO_SERVER_LOGIN_RESPONSE_MISSING_STATUS")
    ND_ERROR ND_E_ECHO_SERVER_LOGIN_RESPONSE_MISSING_VIDEORTCP = ND_ERROR("ND_E_ECHO_SERVER_LOGIN_RESPONSE_MISSING_VIDEORTCP")
    ND_ERROR ND_E_ECHO_SERVER_LOGIN_RESPONSE_MISSING_VIDEORTP = ND_ERROR("ND_E_ECHO_SERVER_LOGIN_RESPONSE_MISSING_VIDEORTP")
    ND_ERROR ND_E_ECHO_SERVER_LOGIN_SEND_FAILED = ND_ERROR("ND_E_ECHO_SERVER_LOGIN_SEND_FAILED")
    ND_ERROR ND_E_ECHO_SERVER_SIP_MALFORMED_TCP_PACKET = ND_ERROR("ND_E_ECHO_SERVER_SIP_MALFORMED_TCP_PACKET")
    ND_ERROR ND_E_ECHO_SERVER_SIP_NO_TCP = ND_ERROR("ND_E_ECHO_SERVER_SIP_NO_TCP")
    ND_ERROR ND_E_ECHO_SERVER_SIP_NO_UDP = ND_ERROR("ND_E_ECHO_SERVER_SIP_NO_UDP")
    ND_ERROR ND_E_ECHO_SERVER_SIP_NO_UDP_OR_TCP = ND_ERROR("ND_E_ECHO_SERVER_SIP_NO_UDP_OR_TCP")
    ND_ERROR ND_E_ECHO_SERVER_SIP_TCP_PACKETS_DIFFERENT = ND_ERROR("ND_E_ECHO_SERVER_SIP_TCP_PACKETS_DIFFERENT")
    ND_ERROR ND_E_ECHO_SERVER_SIP_TCP_PACKETS_DIFFERENT_SIZE = ND_ERROR("ND_E_ECHO_SERVER_SIP_TCP_PACKETS_DIFFERENT_SIZE")
    ND_ERROR ND_E_ECHO_SERVER_SIP_TCP_RECV_FAILED = ND_ERROR("ND_E_ECHO_SERVER_SIP_TCP_RECV_FAILED")
    ND_ERROR ND_E_ECHO_SERVER_SIP_TCP_SEND_FAILED = ND_ERROR("ND_E_ECHO_SERVER_SIP_TCP_SEND_FAILED")
    ND_ERROR ND_E_ECHO_SERVER_SIP_UDP_DATA_DIFFERENT = ND_ERROR("ND_E_ECHO_SERVER_SIP_UDP_DATA_DIFFERENT")
    ND_ERROR ND_E_ECHO_SERVER_SIP_UDP_DIFFERENT_LENGTH = ND_ERROR("ND_E_ECHO_SERVER_SIP_UDP_DIFFERENT_LENGTH")
    ND_ERROR ND_E_ECHO_SERVER_SIP_UDP_RECV_FAILED = ND_ERROR("ND_E_ECHO_SERVER_SIP_UDP_RECV_FAILED")
    ND_ERROR ND_E_ECHO_SERVER_SIP_UDP_SEND_FAILED = ND_ERROR("ND_E_ECHO_SERVER_SIP_UDP_SEND_FAILED")
    ND_ERROR ND_E_ECHO_SERVER_TCP_SET_ASYNC_FAILED = ND_ERROR("ND_E_ECHO_SERVER_TCP_SET_ASYNC_FAILED")
    ND_ERROR ND_E_ECHO_SERVER_UDP_SET_ASYNC_FAILED = ND_ERROR("ND_E_ECHO_SERVER_UDP_SET_ASYNC_FAILED")
    ND_ERROR ND_E_NO_ERROR = ND_ERROR("ND_E_NO_ERROR", VxClientProxyJNI.ND_E_NO_ERROR_get())
    ND_ERROR ND_E_NO_INTERFACE = ND_ERROR("ND_E_NO_INTERFACE")
    ND_ERROR ND_E_NO_INTERFACE_WITH_GATEWAY = ND_ERROR("ND_E_NO_INTERFACE_WITH_GATEWAY")
    ND_ERROR ND_E_NO_INTERFACE_WITH_ROUTE = ND_ERROR("ND_E_NO_INTERFACE_WITH_ROUTE")
    ND_ERROR ND_E_TEST_NOT_RUN = ND_ERROR("ND_E_TEST_NOT_RUN")
    ND_ERROR ND_E_TIMEOUT = ND_ERROR("ND_E_TIMEOUT")
    private Int swigNext = 0
    private ND_ERROR[] swigValues = ND_ERROR[]{ND_E_NO_ERROR, ND_E_TEST_NOT_RUN, ND_E_NO_INTERFACE, ND_E_NO_INTERFACE_WITH_GATEWAY, ND_E_NO_INTERFACE_WITH_ROUTE, ND_E_TIMEOUT, ND_E_CANT_ICMP, ND_E_CANT_RESOLVE_VIVOX_UDP_SERVER, ND_E_CANT_RESOLVE_ROOT_DNS_SERVER, ND_E_CANT_CONVERT_LOCAL_IP_ADDRESS, ND_E_CANT_CONTACT_STUN_SERVER_ON_UDP_PORT_3478, ND_E_CANT_CREATE_TCP_SOCKET, ND_E_CANT_LOAD_ICMP_LIBRARY, ND_E_CANT_FIND_SENDECHO2_PROCADDR, ND_E_CANT_CONNECT_TO_ECHO_SERVER, ND_E_ECHO_SERVER_LOGIN_SEND_FAILED, ND_E_ECHO_SERVER_LOGIN_RECV_FAILED, ND_E_ECHO_SERVER_LOGIN_RESPONSE_MISSING_STATUS, ND_E_ECHO_SERVER_LOGIN_RESPONSE_FAILED_STATUS, ND_E_ECHO_SERVER_LOGIN_RESPONSE_MISSING_SESSIONID, ND_E_ECHO_SERVER_LOGIN_RESPONSE_MISSING_SIPPORT, ND_E_ECHO_SERVER_LOGIN_RESPONSE_MISSING_AUDIORTP, ND_E_ECHO_SERVER_LOGIN_RESPONSE_MISSING_AUDIORTCP, ND_E_ECHO_SERVER_LOGIN_RESPONSE_MISSING_VIDEORTP, ND_E_ECHO_SERVER_LOGIN_RESPONSE_MISSING_VIDEORTCP, ND_E_ECHO_SERVER_CANT_ALLOCATE_SIP_SOCKET, ND_E_ECHO_SERVER_CANT_ALLOCATE_MEDIA_SOCKET, ND_E_ECHO_SERVER_SIP_UDP_SEND_FAILED, ND_E_ECHO_SERVER_SIP_UDP_RECV_FAILED, ND_E_ECHO_SERVER_SIP_TCP_SEND_FAILED, ND_E_ECHO_SERVER_SIP_TCP_RECV_FAILED, ND_E_ECHO_SERVER_SIP_NO_UDP_OR_TCP, ND_E_ECHO_SERVER_SIP_NO_UDP, ND_E_ECHO_SERVER_SIP_NO_TCP, ND_E_ECHO_SERVER_SIP_MALFORMED_TCP_PACKET, ND_E_ECHO_SERVER_SIP_UDP_DIFFERENT_LENGTH, ND_E_ECHO_SERVER_SIP_UDP_DATA_DIFFERENT, ND_E_ECHO_SERVER_SIP_TCP_PACKETS_DIFFERENT, ND_E_ECHO_SERVER_SIP_TCP_PACKETS_DIFFERENT_SIZE, ND_E_ECHO_SERVER_LOGIN_RECV_FAILED_TIMEOUT, ND_E_ECHO_SERVER_TCP_SET_ASYNC_FAILED, ND_E_ECHO_SERVER_UDP_SET_ASYNC_FAILED, ND_E_ECHO_SERVER_CANT_RESOLVE_NAME}
    private String swigName
    private Int swigValue

    private ND_ERROR(String string2) {
        this.swigName = string2
        Int n = swigNext
        swigNext = n + 1
        this.swigValue = n
    }

    private ND_ERROR(String string2, Int n) {
        this.swigName = string2
        this.swigValue = n
        swigNext = n + 1
    }

    private ND_ERROR(String string2, ND_ERROR nD_ERROR) {
        this.swigName = string2
        this.swigValue = nD_ERROR.swigValue
        swigNext = this.swigValue + 1
    }

    /*
     * Enabled force condition propagation
     * Lifted jumps to return sites
     */
    ND_ERROR swigToEnum(Int n) {
        if (n < swigValues.length && n >= 0 && ND_ERROR.swigValues[n].swigValue == n) {
            return swigValues[n]
        }
        Int n2 = 0
        while (n2 < swigValues.length) {
            if (ND_ERROR.swigValues[n2].swigValue == n) {
                return swigValues[n2]
            }
            ++n2
        }
        throw IllegalArgumentException("No enum " + ND_ERROR.class + " with value " + n)
    }

    Int swigValue() {
        return this.swigValue
    }

    String toString() {
        return this.swigName
    }
}

