/*
 * Decompiled with CFR 0.152.
 */
package com.vivox.service

class ND_TEST_TYPE {
    ND_TEST_TYPE ND_TEST_DNS = ND_TEST_TYPE("ND_TEST_DNS")
    ND_TEST_TYPE ND_TEST_ECHO = ND_TEST_TYPE("ND_TEST_ECHO")
    ND_TEST_TYPE ND_TEST_ECHO_MEDIA = ND_TEST_TYPE("ND_TEST_ECHO_MEDIA")
    ND_TEST_TYPE ND_TEST_ECHO_MEDIA_LARGE_PACKET = ND_TEST_TYPE("ND_TEST_ECHO_MEDIA_LARGE_PACKET")
    ND_TEST_TYPE ND_TEST_ECHO_SIP_FIRST_PORT = ND_TEST_TYPE("ND_TEST_ECHO_SIP_FIRST_PORT")
    ND_TEST_TYPE ND_TEST_ECHO_SIP_FIRST_PORT_INVITE_REQUEST = ND_TEST_TYPE("ND_TEST_ECHO_SIP_FIRST_PORT_INVITE_REQUEST")
    ND_TEST_TYPE ND_TEST_ECHO_SIP_FIRST_PORT_INVITE_RESPONSE = ND_TEST_TYPE("ND_TEST_ECHO_SIP_FIRST_PORT_INVITE_RESPONSE")
    ND_TEST_TYPE ND_TEST_ECHO_SIP_FIRST_PORT_REGISTER_REQUEST = ND_TEST_TYPE("ND_TEST_ECHO_SIP_FIRST_PORT_REGISTER_REQUEST")
    ND_TEST_TYPE ND_TEST_ECHO_SIP_FIRST_PORT_REGISTER_RESPONSE = ND_TEST_TYPE("ND_TEST_ECHO_SIP_FIRST_PORT_REGISTER_RESPONSE")
    ND_TEST_TYPE ND_TEST_ECHO_SIP_SECOND_PORT = ND_TEST_TYPE("ND_TEST_ECHO_SIP_SECOND_PORT")
    ND_TEST_TYPE ND_TEST_ECHO_SIP_SECOND_PORT_INVITE_REQUEST = ND_TEST_TYPE("ND_TEST_ECHO_SIP_SECOND_PORT_INVITE_REQUEST")
    ND_TEST_TYPE ND_TEST_ECHO_SIP_SECOND_PORT_INVITE_RESPONSE = ND_TEST_TYPE("ND_TEST_ECHO_SIP_SECOND_PORT_INVITE_RESPONSE")
    ND_TEST_TYPE ND_TEST_ECHO_SIP_SECOND_PORT_REGISTER_REQUEST = ND_TEST_TYPE("ND_TEST_ECHO_SIP_SECOND_PORT_REGISTER_REQUEST")
    ND_TEST_TYPE ND_TEST_ECHO_SIP_SECOND_PORT_REGISTER_RESPONSE = ND_TEST_TYPE("ND_TEST_ECHO_SIP_SECOND_PORT_REGISTER_RESPONSE")
    ND_TEST_TYPE ND_TEST_LOCATE_INTERFACE = ND_TEST_TYPE("ND_TEST_LOCATE_INTERFACE")
    ND_TEST_TYPE ND_TEST_PING_GATEWAY = ND_TEST_TYPE("ND_TEST_PING_GATEWAY")
    ND_TEST_TYPE ND_TEST_STUN = ND_TEST_TYPE("ND_TEST_STUN")
    private Int swigNext = 0
    private ND_TEST_TYPE[] swigValues = ND_TEST_TYPE[]{ND_TEST_LOCATE_INTERFACE, ND_TEST_PING_GATEWAY, ND_TEST_DNS, ND_TEST_STUN, ND_TEST_ECHO, ND_TEST_ECHO_SIP_FIRST_PORT, ND_TEST_ECHO_SIP_FIRST_PORT_INVITE_REQUEST, ND_TEST_ECHO_SIP_FIRST_PORT_INVITE_RESPONSE, ND_TEST_ECHO_SIP_FIRST_PORT_REGISTER_REQUEST, ND_TEST_ECHO_SIP_FIRST_PORT_REGISTER_RESPONSE, ND_TEST_ECHO_SIP_SECOND_PORT, ND_TEST_ECHO_SIP_SECOND_PORT_INVITE_REQUEST, ND_TEST_ECHO_SIP_SECOND_PORT_INVITE_RESPONSE, ND_TEST_ECHO_SIP_SECOND_PORT_REGISTER_REQUEST, ND_TEST_ECHO_SIP_SECOND_PORT_REGISTER_RESPONSE, ND_TEST_ECHO_MEDIA, ND_TEST_ECHO_MEDIA_LARGE_PACKET}
    private String swigName
    private Int swigValue

    private ND_TEST_TYPE(String string2) {
        this.swigName = string2
        Int n = swigNext
        swigNext = n + 1
        this.swigValue = n
    }

    private ND_TEST_TYPE(String string2, Int n) {
        this.swigName = string2
        this.swigValue = n
        swigNext = n + 1
    }

    private ND_TEST_TYPE(String string2, ND_TEST_TYPE nD_TEST_TYPE) {
        this.swigName = string2
        this.swigValue = nD_TEST_TYPE.swigValue
        swigNext = this.swigValue + 1
    }

    /*
     * Enabled force condition propagation
     * Lifted jumps to return sites
     */
    ND_TEST_TYPE swigToEnum(Int n) {
        if (n < swigValues.length && n >= 0 && ND_TEST_TYPE.swigValues[n].swigValue == n) {
            return swigValues[n]
        }
        Int n2 = 0
        while (n2 < swigValues.length) {
            if (ND_TEST_TYPE.swigValues[n2].swigValue == n) {
                return swigValues[n2]
            }
            ++n2
        }
        throw IllegalArgumentException("No enum " + ND_TEST_TYPE.class + " with value " + n)
    }

    Int swigValue() {
        return this.swigValue
    }

    String toString() {
        return this.swigName
    }
}

