/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const linkpoint_free_buffer: (a: number) => void;
export const linkpoint_llsd_parse_binary: (a: number, b: number) => number;
export const linkpoint_llsd_parse_notation: (a: number, b: number) => number;
export const linkpoint_llsd_parse_xml: (a: number, b: number) => number;
export const linkpoint_llsd_serialize_binary: (a: number, b: number) => number;
export const linkpoint_llsd_serialize_notation: (a: number, b: number) => number;
export const linkpoint_llsd_serialize_xml: (a: number, b: number) => number;
export const __wbg_wasmmatrix4_free: (a: number, b: number) => void;
export const __wbg_wasmquaternion_free: (a: number, b: number) => void;
export const wasm_generate_volume: (a: number, b: number, c: number, d: number) => void;
export const wasm_parse_binary: (a: number, b: number, c: number) => void;
export const wasm_parse_j2k_header: (a: number, b: number, c: number) => void;
export const wasm_parse_notation: (a: number, b: number, c: number) => void;
export const wasm_parse_xml: (a: number, b: number, c: number) => void;
export const wasm_serialize_binary: (a: number, b: number, c: number) => void;
export const wasm_serialize_notation: (a: number, b: number, c: number) => void;
export const wasm_serialize_xml: (a: number, b: number, c: number) => void;
export const wasmmatrix4_from_quaternion: (a: number) => number;
export const wasmmatrix4_identity: () => number;
export const wasmmatrix4_transform_point: (a: number, b: number, c: number, d: number, e: number) => void;
export const wasmquaternion_identity: () => number;
export const wasmquaternion_new: (a: number, b: number, c: number, d: number) => number;
export const wasmquaternion_normalize: (a: number) => number;
export const wasmquaternion_rotate_vector3: (a: number, b: number, c: number, d: number, e: number) => void;
export const wasmquaternion_slerp: (a: number, b: number, c: number) => number;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number, b: number, c: number) => void;
