// Generated Design Tokens from tokens.json.
// DO NOT EDIT DIRECTLY. Generated by tools/token_gen/cli.py

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct RgbaColor {
    pub r: f32,
    pub g: f32,
    pub b: f32,
    pub a: f32,
}

impl RgbaColor {
    pub const fn new(r: f32, g: f32, b: f32, a: f32) -> Self {
        Self { r, g, b, a }
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ColorTokens {
    pub status: StatusTokens,
    pub editor: EditorTokens,
    pub scene: SceneTokens,
    pub aurora: AuroraTokens,
    pub glass: GlassTokens,
    pub coord_color: RgbaColor,
    pub on_surface_dim: RgbaColor,
    pub outline_subtle: RgbaColor,
    pub unread_badge: RgbaColor,
    pub on_unread_badge: RgbaColor,
    pub hud_background: RgbaColor,
    pub hud_stroke: RgbaColor,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct StatusTokens {
    pub online: RgbaColor,
    pub offline: RgbaColor,
    pub degraded: RgbaColor,
    pub unknown: RgbaColor,
    pub success: RgbaColor,
    pub warning: RgbaColor,
    pub unsaved: RgbaColor,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct EditorTokens {
    pub appbar_background: RgbaColor,
    pub background: RgbaColor,
    pub panel_background: RgbaColor,
    pub divider: RgbaColor,
    pub text: RgbaColor,
    pub text_muted: RgbaColor,
    pub text_dim: RgbaColor,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SceneTokens {
    pub background: RgbaColor,
    pub shadow: RgbaColor,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct AuroraTokens {
    pub color1: RgbaColor,
    pub color2: RgbaColor,
    pub color3: RgbaColor,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct GlassTokens {
    pub background: RgbaColor,
    pub stroke: RgbaColor,
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Tokens {
    pub color: ColorTokens,
}

pub const GENERATED_TOKENS: Tokens = Tokens {
    color: ColorTokens {
        status: StatusTokens {
            online: RgbaColor::new(0.298039, 0.686275, 0.313725, 1.0),
            offline: RgbaColor::new(0.956863, 0.262745, 0.211765, 1.0),
            degraded: RgbaColor::new(1.0, 0.596078, 0.0, 1.0),
            unknown: RgbaColor::new(0.619608, 0.619608, 0.619608, 1.0),
            success: RgbaColor::new(0.486275, 1.0, 0.847059, 1.0),
            warning: RgbaColor::new(1.0, 0.835294, 0.427451, 1.0),
            unsaved: RgbaColor::new(1.0, 0.596078, 0.0, 1.0),
        },
        editor: EditorTokens {
            appbar_background: RgbaColor::new(0.145098, 0.145098, 0.14902, 1.0),
            background: RgbaColor::new(0.117647, 0.117647, 0.117647, 1.0),
            panel_background: RgbaColor::new(0.176471, 0.176471, 0.176471, 1.0),
            divider: RgbaColor::new(0.235294, 0.235294, 0.235294, 1.0),
            text: RgbaColor::new(0.831373, 0.831373, 0.831373, 1.0),
            text_muted: RgbaColor::new(0.690196, 0.690196, 0.690196, 1.0),
            text_dim: RgbaColor::new(0.501961, 0.501961, 0.501961, 1.0),
        },
        scene: SceneTokens {
            background: RgbaColor::new(0.0, 0.0, 0.0, 1.0),
            shadow: RgbaColor::new(0.0, 0.0, 0.0, 0.533333),
        },
        aurora: AuroraTokens {
            color1: RgbaColor::new(0.427451, 0.909804, 1.0, 0.219608),
            color2: RgbaColor::new(0.54902, 0.486275, 1.0, 0.219608),
            color3: RgbaColor::new(0.486275, 1.0, 0.847059, 0.156863),
        },
        glass: GlassTokens {
            background: RgbaColor::new(0.062745, 0.109804, 0.2, 0.54902),
            stroke: RgbaColor::new(1.0, 1.0, 1.0, 0.078431),
        },
        coord_color: RgbaColor::new(0.709804, 0.780392, 0.913725, 1.0),
        on_surface_dim: RgbaColor::new(0.709804, 0.780392, 0.913725, 1.0),
        outline_subtle: RgbaColor::new(0.2, 0.262745, 0.392157, 1.0),
        unread_badge: RgbaColor::new(0.427451, 0.909804, 1.0, 1.0),
        on_unread_badge: RgbaColor::new(0.011765, 0.129412, 0.164706, 1.0),
        hud_background: RgbaColor::new(0.0, 0.0, 0.0, 0.666667),
        hud_stroke: RgbaColor::new(1.0, 1.0, 1.0, 0.2),
    },
};
