// @generated by `cargo run -p linkpoint-core --example generate_contract`.
// Do not edit by hand; Rust is the contract source of truth.
package com.linkpoint.protocol

enum class GridKind { SECOND_LIFE, OPENSIM }

data class LoginRequestContract(
    val grid: GridKind,
    val loginUri: String,
    val username: String,
    val password: String,
    val start: String? = null
)

data class SessionSnapshotContract(
    val agentId: String,
    val sessionId: String,
    val regionName: String
)
