from abc import ABC, abstractmethod
from typing import Dict, Any
from tools.protocol_gen.proto_ast.models import ProtocolAST

HEADER_WARNING = """/*
 * AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
 * Generated by Linkpoint Unified CLI Code Generator (protocol-gen).
 * Source: schemas/protocol/
 */
"""

class BaseEmitter(ABC):
    """
    Abstract base class for all target language code emitters.
    """

    def __init__(self, target_name: str, file_extension: str):
        self.target_name = target_name
        self.file_extension = file_extension

    @abstractmethod
    def emit(self, ast: ProtocolAST, out_dir: str) -> Dict[str, str]:
        """
        Emits generated code files.
        Returns a dict mapping file paths to file contents.
        """
        pass

    def get_header_warning(self, comment_prefix: str = "//") -> str:
        if comment_prefix == "/*":
            return HEADER_WARNING
        lines = [
            f"{comment_prefix} AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.",
            f"{comment_prefix} Generated by Linkpoint Unified CLI Code Generator (protocol-gen).",
            f"{comment_prefix} Source: schemas/protocol/"
        ]
        return "\n".join(lines) + "\n\n"
