// Generated Design Tokens from tokens.json.
// DO NOT EDIT DIRECTLY. Generated by tools/token_gen/cli.py

import 'package:flutter/material.dart';

abstract class GeneratedTokens {
  static const color = _ColorTokens();
}

class _ColorTokens {
  const _ColorTokens();

  final status = const _StatusTokens();
  final editor = const _EditorTokens();
  final scene = const _SceneTokens();
  final aurora = const _AuroraTokens();
  final glass = const _GlassTokens();
  final coordColor = const Color(0xFFB5C7E9);
  final onSurfaceDim = const Color(0xFFB5C7E9);
  final outlineSubtle = const Color(0xFF334364);
  final unreadBadge = const Color(0xFF6DE8FF);
  final onUnreadBadge = const Color(0xFF03212A);
  final hudBackground = const Color(0xAA000000);
  final hudStroke = const Color(0x33FFFFFF);
  final brand = const _BrandTokens();
  final ui = const _UiTokens();
}

class _StatusTokens {
  const _StatusTokens();

  final online = const Color(0xFF4CAF50);
  final offline = const Color(0xFFF44336);
  final degraded = const Color(0xFFFF9800);
  final unknown = const Color(0xFF9E9E9E);
  final success = const Color(0xFF7CFFD8);
  final warning = const Color(0xFFFFD56D);
  final unsaved = const Color(0xFFFF9800);
}

class _EditorTokens {
  const _EditorTokens();

  final appbarBackground = const Color(0xFF252526);
  final background = const Color(0xFF1E1E1E);
  final panelBackground = const Color(0xFF2D2D2D);
  final divider = const Color(0xFF3C3C3C);
  final text = const Color(0xFFD4D4D4);
  final textMuted = const Color(0xFFB0B0B0);
  final textDim = const Color(0xFF808080);
}

class _SceneTokens {
  const _SceneTokens();

  final background = const Color(0xFF000000);
  final shadow = const Color(0x88000000);
}

class _AuroraTokens {
  const _AuroraTokens();

  final color1 = const Color(0x386DE8FF);
  final color2 = const Color(0x388C7CFF);
  final color3 = const Color(0x287CFFD8);
}

class _GlassTokens {
  const _GlassTokens();

  final background = const Color(0x8C101C33);
  final stroke = const Color(0x14FFFFFF);
}

class _BrandTokens {
  const _BrandTokens();

  final primary = const Color(0xFF007AFF);
  final secondary = const Color(0xFF5856D6);
  final accent = const Color(0xFFAF52DE);
}

class _UiTokens {
  const _UiTokens();

  final text = const Color(0xFFFFFFFF);
  final textMuted = const Color(0x99EBEBF5);
  final textSecondary = const Color(0xFF8E8E93);
  final background = const Color(0xFF000000);
  final surface = const Color(0xFF1C1C1E);
  final cardBackground = const Color(0xFF2C2C2E);
  final error = const Color(0xFFFF3B30);
  final disabled = const Color(0xFF8E8E93);
  final shadow = const Color(0x1A000000);
  final viewportPlaceholder = const Color(0x4D8E8E93);
}
