// @generated by `cargo run -p linkpoint-core --example generate_contract`.
// Do not edit by hand; Rust is the contract source of truth.

enum GridKind { secondLife, openSim }

class ContractLoginRequest {
  final GridKind grid;
  final String loginUri;
  final String username;
  final String password;
  final String? start;

  const ContractLoginRequest({
    required this.grid,
    required this.loginUri,
    required this.username,
    required this.password,
    this.start,
  });
}

class ContractSessionSnapshot {
  final String agentId;
  final String sessionId;
  final String regionName;

  const ContractSessionSnapshot({
    required this.agentId,
    required this.sessionId,
    required this.regionName,
  });
}
