//! Generates the frontend contract from the Rust-owned wire schema.
//!
//! Keep this template adjacent to the serde types in this crate. CI regenerates
//! it and rejects drift, so TypeScript is never an independently edited schema.

use std::{fs, path::PathBuf};

fn main() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
    let ts_target = root.join("packages/viewer-types/src/index.ts");
    fs::write(ts_target, TS_CONTRACT).expect("write generated TS Viewer contract");

    let dart_target = root.join("packages/linkpoint_dart/lib/src/viewer_contract.g.dart");
    if let Some(parent) = dart_target.parent() {
        let _ = fs::create_dir_all(parent);
    }
    fs::write(dart_target, DART_CONTRACT).expect("write generated Dart Viewer contract");

    let mut kt_target =
        root.join("legacy/Linkpoint/src/main/java/com/linkpoint/protocol/ViewerContract.kt");
    if !kt_target.parent().map(|p| p.exists()).unwrap_or(false) {
        kt_target = root.join("Linkpoint/src/main/java/com/linkpoint/protocol/ViewerContract.kt");
    }
    if let Some(parent) = kt_target.parent() {
        let _ = fs::create_dir_all(parent);
    }
    fs::write(kt_target, KT_CONTRACT).expect("write generated Kotlin Viewer contract");
}

const TS_CONTRACT: &str = r#"// @generated by `cargo run -p linkpoint-core --example generate_contract`.
// Do not edit by hand; Rust is the contract source of truth.
export type GridKind = "second-life" | "opensim";

export interface LoginRequest {
  readonly grid: GridKind;
  readonly loginUri: string;
  readonly username: string;
  readonly password: string;
  readonly start?: string;
}

export interface SessionSnapshot {
  readonly agentId: string;
  readonly sessionId: string;
  readonly regionName: string;
}

export interface ChatMessage {
  readonly id: string;
  readonly fromId: string;
  readonly fromName: string;
  readonly body: string;
  readonly timestamp: string;
}

export interface TextureTransform {
  readonly offset?: readonly [number, number];
  readonly scale?: readonly [number, number];
  readonly rotation?: number;
}

export interface PbrMaterialAttributes {
  readonly metallic?: number;
  readonly roughness?: number;
  readonly baseColor?: readonly [number, number, number, number];
  readonly emissiveColor?: readonly [number, number, number];
  readonly metallicRoughnessTextureUri?: string;
  readonly baseColorTextureUri?: string;
  readonly normalMapUri?: string;
  readonly emissiveTextureUri?: string;
  readonly textureTransform?: TextureTransform;
}

export interface JointInfluence {
  readonly jointName: string;
  readonly weight: number;
}

export interface SkinningMetadata {
  readonly skeletonRootId?: string;
  readonly joints?: readonly JointInfluence[];
}

export interface SceneEntity {
  readonly id: string;
  readonly parentId?: string;
  readonly position: readonly [number, number, number];
  readonly rotation?: readonly [number, number, number, number];
  readonly scale?: readonly [number, number, number];
  readonly meshUri?: string;
  readonly material?: PbrMaterialAttributes;
  readonly skinning?: SkinningMetadata;
}

export type ViewerCommand =
  | { readonly type: "session.login"; readonly payload: LoginRequest }
  | { readonly type: "session.logout" }
  | { readonly type: "session.reconnect" }
  | { readonly type: "lifecycle.suspend" }
  | { readonly type: "lifecycle.resume" }
  | { readonly type: "network.changed"; readonly payload: { readonly online: boolean } }
  | { readonly type: "chat.send"; readonly payload: { readonly body: string } }
  | { readonly type: "object.touch"; readonly payload: { readonly objectId: string; readonly face?: number } };

export type ViewerEvent =
  | { readonly type: "session.connecting" }
  | { readonly type: "session.connected"; readonly payload: SessionSnapshot }
  | { readonly type: "session.disconnected"; readonly payload: { readonly reason: string } }
  | { readonly type: "session.reconnecting"; readonly payload: { readonly attempt: number } }
  | { readonly type: "session.error"; readonly payload: { readonly code: string; readonly message: string } }
  | { readonly type: "chat.received"; readonly payload: ChatMessage }
  | { readonly type: "scene.snapshot"; readonly payload: readonly SceneEntity[] }
  | { readonly type: "scene.upsert"; readonly payload: SceneEntity }
  | { readonly type: "scene.remove"; readonly payload: { readonly id: string } };
"#;

const DART_CONTRACT: &str = r#"// @generated by `cargo run -p linkpoint-core --example generate_contract`.
// Do not edit by hand; Rust is the contract source of truth.

enum GridKind { secondLife, openSim }

class ContractLoginRequest {
  final GridKind grid;
  final String loginUri;
  final String username;
  final String password;
  final String? start;

  const ContractLoginRequest({
    required this.grid,
    required this.loginUri,
    required this.username,
    required this.password,
    this.start,
  });
}

class ContractSessionSnapshot {
  final String agentId;
  final String sessionId;
  final String regionName;

  const ContractSessionSnapshot({
    required this.agentId,
    required this.sessionId,
    required this.regionName,
  });
}
"#;

const KT_CONTRACT: &str = r#"// @generated by `cargo run -p linkpoint-core --example generate_contract`.
// Do not edit by hand; Rust is the contract source of truth.
package com.linkpoint.protocol

enum class GridKind { SECOND_LIFE, OPENSIM }

data class LoginRequestContract(
    val grid: GridKind,
    val loginUri: String,
    val username: String,
    val password: String,
    val start: String? = null
)

data class SessionSnapshotContract(
    val agentId: String,
    val sessionId: String,
    val regionName: String
)
"#;
