//! Generates the frontend contract from the Rust-owned wire schema.
//!
//! Keep this template adjacent to the serde types in this crate. CI regenerates
//! it and rejects drift, so TypeScript is never an independently edited schema.

use std::{fs, path::PathBuf};

fn main() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
    let target = root.join("packages/viewer-types/src/index.ts");
    fs::write(target, CONTRACT).expect("write generated Viewer contract");
}

const CONTRACT: &str = r#"// @generated by `cargo run -p linkpoint-core --example generate_contract`.
// Do not edit by hand; Rust is the contract source of truth.
export type GridKind = "second-life" | "opensim";

export interface LoginRequest {
  readonly grid: GridKind;
  readonly loginUri: string;
  readonly username: string;
  readonly password: string;
  readonly start?: string;
}

export interface SessionSnapshot {
  readonly agentId: string;
  readonly sessionId: string;
  readonly regionName: string;
}

export interface ChatMessage {
  readonly id: string;
  readonly fromId: string;
  readonly fromName: string;
  readonly body: string;
  readonly timestamp: string;
}

export interface SceneEntity {
  readonly id: string;
  readonly parentId?: string;
  readonly position: readonly [number, number, number];
  readonly rotation?: readonly [number, number, number, number];
  readonly scale?: readonly [number, number, number];
}

export type ViewerCommand =
  | { readonly type: "session.login"; readonly payload: LoginRequest }
  | { readonly type: "session.logout" }
  | { readonly type: "session.reconnect" }
  | { readonly type: "lifecycle.suspend" }
  | { readonly type: "lifecycle.resume" }
  | { readonly type: "network.changed"; readonly payload: { readonly online: boolean } }
  | { readonly type: "chat.send"; readonly payload: { readonly body: string } }
  | { readonly type: "object.touch"; readonly payload: { readonly objectId: string; readonly face?: number } };

export type ViewerEvent =
  | { readonly type: "session.connecting" }
  | { readonly type: "session.connected"; readonly payload: SessionSnapshot }
  | { readonly type: "session.disconnected"; readonly payload: { readonly reason: string } }
  | { readonly type: "session.reconnecting"; readonly payload: { readonly attempt: number } }
  | { readonly type: "session.error"; readonly payload: { readonly code: string; readonly message: string } }
  | { readonly type: "chat.received"; readonly payload: ChatMessage }
  | { readonly type: "scene.snapshot"; readonly payload: readonly SceneEntity[] }
  | { readonly type: "scene.upsert"; readonly payload: SceneEntity }
  | { readonly type: "scene.remove"; readonly payload: { readonly id: string } };
"#;
